#!/usr/bin/env zsh

if [ $# -lt 1 ] || [ $# -gt 3 ]; then
    >&2 echo "Usage: $0 <file.req> [port=80] [ip=localhost]"
    return 1
fi

if [ -z "$2" ]; then
    2="8081"
fi

if [ -z "$3" ]; then
    3="127.0.0.1"
fi

if ! [ -e "$1" ]; then
    >&2 echo "File does not exist"
    return 1
fi

if ! [ -s "$1" ]; then
    >&2 echo "Empty file"
    return 1
fi

>&2 echo "__________________________________________\n"
>&2 echo "RUN: cat $1 | nc $3 $2"
>&2 echo "__________________________________________\n"
>&2 echo "SEND REQUEST: \n" ; cat $1
>&2 echo "__________________________________________\n"
>&2 echo "Response: \n"
cat $1 | nc $3 $2
>&2 echo "__________________________________________\n"
